module.exports = [
    {
        name: 'Snatch',
        description: 'classic snatch',
        musclesWorked: ['Quadriceps', 'Hamstrings', 'Glutes', 'Deltoids', 'Upper Back', 'Lower Back'],
        type: 'weighted',
        createdBy: null,
    },
    {
        name: 'Clean and Jerk',
        description: 'classic clean and jerk',
        musclesWorked: ['Quadriceps', 'Hamstrings', 'Glutes', 'Deltoids', 'Triceps', 'Upper Back', 'Lower Back'],
        type: 'weighted',
        createdBy: null,
    },
    {
        name: 'Back Squat',
        description: 'a barbell squat',
        musclesWorked: ['Quadriceps', 'Hamstrings', 'Glutes', 'Lower Back'],
        type: 'weighted',
        createdBy: null,
    },
    {
        name: 'Bench Press',
        description: 'a barbell press performed while laying down on a bench',
        musclesWorked: ['Chest', 'Deltoids', 'Triceps'],
        type: 'weighted',
        createdBy: null,
    },
    {
        name: 'Deadlift',
        description: 'a barbell deadlift',
        musclesWorked: ['Lower Back', 'Glutes', 'Hamstrings', 'Upper Back', 'Abdominals'],
        type: 'weighted',
        createdBy: null,
    },
    {
        name: 'Front Squat',
        description: 'a barbell squat with the bar on top of shoulders and in front of neck',
        musclesWorked: ['Quadriceps', 'Hamstrings', 'Glutes', 'Lower Back', 'Upper Back', 'Abdominals'],
        type: 'weighted',
        createdBy: null,
    },
    {
        name: 'Strict Press',
        description: 'a barbell overhead press performed while standing',
        musclesWorked: ['Deltoids', 'Triceps'],
        type: 'weighted',
        createdBy: null,
    },
    {
        name: 'Push Press',
        description: 'a barbell overhead press performed while standing and using momentum from your legs',
        musclesWorked: ['Deltoids', 'Triceps', 'Quadriceps'],
        type: 'weighted',
        createdBy: null,
    },
    {
        name: 'Power Snatch',
        description: 'a classic snatch from the floor caught above parallel',
        musclesWorked: ['Quadriceps', 'Hamstrings', 'Glutes', 'Deltoids', 'Upper Back', 'Lower Back'],
        type: 'weighted',
        createdBy: null,
    },
    {
        name: 'Power Clean',
        description: 'a classic clean from the floor caught above parallel',
        musclesWorked: ['Quadriceps', 'Hamstrings', 'Glutes', 'Upper Back', 'Lower Back'],
        type: 'weighted',
        createdBy: null,
    },
    {
        name: 'Running',
        description: 'a classic run',
        musclesWorked: ['Quadriceps', 'Hamstrings', 'Glutes', 'Calves', 'Abdominals'],
        type: 'cardio',
        createdBy: null,
    },
];
